image: ubuntu:16.04

cache:
  key: apt-cache
  paths:
  - apt-cache/

stages:
- build

before_script:
- export APT_CACHE_DIR=`pwd`/apt-cache && mkdir -pv $APT_CACHE_DIR
- apt-get update -qq
- apt-get -o dir::cache::archives="$APT_CACHE_DIR" install -y build-essential cmake

build_TM:
  stage: build
  script:
  - mkdir build && cd build
  - cmake ../
  - make -j32
  artifacts:
    paths:
    - bin
