image: ubuntu:16.04

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  
cache:
  key: apt-cache
  paths:
  - apt-cache/

stages:
- build

before_script:
- export APT_CACHE_DIR=`pwd`/apt-cache && mkdir -pv $APT_CACHE_DIR
- apt-get update -qq
- apt-get -o dir::cache::archives="$APT_CACHE_DIR" install -y qtbase5-dev libqt5svg5-dev qt5-default qtdeclarative5-dev

build_TM:
  stage: build
  script:
  - mkdir build && cd build
  - cmake ../
  - make -j32
  artifacts:
    paths:
    - bin
